name: Build and deploy to aliyun

on:
  push:
    branches: ['master']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 23
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
      - name: Deploy web to aliyun
        uses: easingthemes/ssh-deploy@v3
        with:
          SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SEVER_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "public/"
          REMOTE_HOST: "fluctus.cc"
          REMOTE_USER: "root"
          TARGET: "/root/Webs/Fluctus-blog/"